### ISSUE TITLE
Non-latin characters are not supported in filenames generated by default templates

### ISSUE THREAD

**Issue by ajmz** [coddingtonbear/obsidian-web#11] opened 2022-04-27 10:06 UTC
Page titles with English languages display properly, but East Asian languages display nothing, v1.3.5.

**Comment by coddingtonbear** [comment] 2022-04-27 14:08
I _assume_ by this you mean that you can't name your file using an non-latin language, because I can confirm that we're able to extract the title from arbitrary pages; here's an example from asahi.com:

![image](https://user-images.githubusercontent.com/527661/165534235-7864801a-8075-4c2d-b6c4-9a106e77e225.png)

You'll see the page title displayed on the first line of content there: "朝日新聞デジタル：朝日新聞社のニュースサイト".

Assuming what you're commenting on _is_ actually just that no filename is populated when your page's title is using a non-latin script, this is an easy thing for you to address on your own.  If you examine whichever template you're using, you'll probably find that the default "API URL" field reads something like this:

```
/vault/{{filename page.title}}.md
```

The `filename` function in use there will strip many filename-unsafe characters from the page title (see https://github.com/coddingtonbear/obsidian-web/blob/2640a2eed155d864cf8af0d1ee1b051a1e8340bf/src/handlebars.ts#L32 for the actual regular expression).  It's not exactly clear to me why that function would strip non-latin characters, but feel free to post a pull request addressing that if you happen to know asolution.

If you're sure that the characters in whatever pages' titles you're visiting are safe and supported filenames on your operating system and within Obsidian itself, you are free to change that template to instead read:

```
/vault/{{page.title}}.md
```

If you do so, we will _not_ process the page title using the aforementioned `filename` function, and it'll include all characters present in the title as they are.  You may find that sometimes requests fail if your operating system or obsidian itself does not support the characters present through all of the many layers between this plugin and your filesystem, but you can also manually remove filename-unsafe characters manually before submission.

**Comment by ajmz** [comment] 2022-04-27 14:47
I did it by use "/vault/{{page.title}}.md", thanks.

**Comment by coddingtonbear** [comment] 2022-04-28 03:50
Actually -- I spent a little time looking into this this evening and couldn't reproduce it after some changes to how I'm handling template rendering.  This _seems_ to work as-is, and that makes me think the problem you were running into was caused by the same thing that was causing #9.

Since I've now fixed that, I'm going to close this as it has now been fixed in the development branch.

**Closed by coddingtonbear** 2022-04-28 03:50 UTC
Labels: enhancement
